### ISSUE TITLE
Reliability on high eccentricity orbit data

### ISSUE THREAD

**Issue by zhexingli** [mzechmeister/GLS#11]
Hello again, a quick question. I understand that a normal periodogram might have some trouble running on radial velocity data for higly eccentric orbits. Could you provide some insights on how reliable this periodogram is when run on high eccentricity data? Thanks.

**Comment by mzechmeister** [comment]
That is a tricky question. As a short answer, your are probably happy with the GLS upto eccentricities 0.3-0.4.
The higher eccentricities, the less efficient the GLS (which is designed for sinusoids). Moreover, the detectability will depend on the number of data, time coverage, and signal-to-noise. With simulations one could study the dependence.
You can adapt the model to Keplerian orbits, at the cost of speed. In the [paper](https://arxiv.org/pdf/0901.2573.pdf), we discuss the Keplerian periodogram, which is included only the original fortran version available [here](http://www.astro.physik.uni-goettingen.de/~zechmeister/gls.php).

Mostly, planet search tools still use GLS-like periograms as start guess or explore the likelihood in a random fashion.
Links for further reading:
https://ui.adsabs.harvard.edu/abs/2015MNRAS.446.1478B
https://ui.adsabs.harvard.edu/abs/2017ApJ...837...20P

**Comment by zhexingli** [comment]
Thx for the answer! Sorry that I forgot to reply because I was on travel and this quickly sank to the bottom of loads of emails... this is very helpful!
