### ISSUE TITLE
Error importing data in web version

### ISSUE THREAD

**Issue by PideaLtd** [mzechmeister/GLS#16]
Importing a three column test file produces the following error in the developer console:

gls.html:46 Uncaught TypeError: line.split is not a function at parse (gls.html:46) at FileReader.loadHandler (read-csv.js:35)

Changing from spaces to pluses as separators makes no difference.

**Comment by mzechmeister** [comment]
Yes, I already noted this problem in #15.

If you download the file and remove the absolute path in
https://github.com/mzechmeister/GLS/blob/931a418e6ca2f414e0885ab4aae60d35ebb071c0/javascript/gls.html#L70-L71
then it will run on your server or locally in your browser.

**Comment by mzechmeister** [comment]
Fixed in 78228a1.
