### ISSUE TITLE
gls.py - `self.plot` method failed with `maplotlib` >= 3.6

### ISSUE THREAD

**Issue by Ciro7** [mzechmeister/GLS#22]
Hello, I hope this can help.

(Note: I'm not an expert programmer. Sorry if explanations are not clear enough, or reporting procedures not strictly followed)

**Issue:**
After an upgrade to `matplotlib` version 3.6.2, the `self.plot` method fails in https://github.com/mzechmeister/GLS/blob/97209080065fc53549fc9781cbdc652e3acaf2b7/python/gls.py

The following code was run in a Jupyter Notebook, by importing and using `Gls` class from https://github.com/mzechmeister/GLS/blob/97209080065fc53549fc9781cbdc652e3acaf2b7/python/gls.py

`fig = gls.plot(block=False, period=False, fap=None, gls=True, data=True, residuals=True);`

and failed with error:

AttributeError                            Traceback (most recent call last)
Cell In[29], line 1
----> 1 fig = gls.plot(block=False, period=False, fap=None, gls=True, data=True, residuals=True)

File c:\users\ciroe\gls.py:499, in Gls.plot(self, block, period, fap, gls, data, residuals)
    496 fbest, T0 = self.best["f"], self.best["T0"]
    498 fig = mpl.figure()
--> 499 fig.canvas.set_window_title('GLS periodogram')
    500 fig.subplots_adjust(hspace=0.05, wspace=0.04, right=0.97, bottom=0.09, top=0.84)
    501 fs = 10   # fontsize

AttributeError: 'FigureCanvasAgg' object has no attribute 'set_window_title'

**Analysis:**
I think this is similar to an issue seen on another repo:
https://github.com/raysect/source/issues/383

Which probably traces back to this root cause (deprecation of the `canvas.set_window_title` method in `matplotlib` >= 3.6):
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.4.0.html#backend-deprecations

**Suggested solution:**
Replace the line:
https://github.com/mzechmeister/GLS/blob/97209080065fc53549fc9781cbdc652e3acaf2b7/python/gls.py#L499

with this other line:
`        fig.canvas.manager.set_window_title('GLS periodogram')`

It worked for me locally, but I did not make a full regression testing on the fix, so I cannot be sure about the backwards compatibility of the fix. Not sure if the issue is that simple to solve, or it is better to just include a warning about this dependency, so that a `matplotlib` < 3.6 environment should be configured for the use of https://github.com/mzechmeister/GLS/blob/97209080065fc53549fc9781cbdc652e3acaf2b7/python/gls.py

Best regards,

Ciro.

**Comment by mzechmeister** [comment]
Hi Ciro,

Thanks a lot for this detailed report and the fix suggestion!
It fully solved the problem. I found compatibility backwards to at least py2.7 + mpl 2.2.5.

Cheers,
Mathias
