### ISSUE TITLE
Applying GLS to Keplerian function

### ISSUE THREAD

**Issue by telmonteiro** [mzechmeister/GLS#23]
I am trying to apply the GLS algorithm (from here [https://pyastronomy.readthedocs.io/en/latest/pyTimingDoc/pyPeriodDoc/gls.html#]) to two sets of RV(t) data. The first one is a planet with a circular orbit with a signal function of the type

$$ RV(t) = K \sin (2\pi(t-T)/P) + \gamma $$

For this simple function, had no problem in applying the GLS. The second set of RV(t) data was from an eccentric orbit (around e=0.4) with a signal function of the type:

$$ RV (\nu) = \gamma + K[e \cos \omega + \cos (\omega + \nu(t))] $$

For this one I'm not able to apply the GLS, even after checking the original paper. Is there some simple and direct way of applying the GLS so I can obtain the orbital parameters and their errors?

**Comment by mzechmeister** [comment]
The task of GLS is to find periods, albeit various versions also estimate parameter errors.
For very eccentric orbits you may still find the period or a harmonic with the GLS (e=0.4 is moderate eccentric).
The Keplerian version (much slower), which is also described in the paper, is only implemented in the [fortran version](https://github.com/mzechmeister/GLS/tree/master/fortran) and a final fit can be done with a gnuplot script, which also should provided least square fit errors.

For more sophicated orbit fitting you may consider other packages, e.g. [exostriker](https://github.com/3fon3fonov/exostriker). For period search they often employ the GLS, too.

**Comment by telmonteiro** [comment]
Thank you kindly for your answer. I will look into it!
